# Generated by Django 2.0.7 on 2018-07-20 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_task_statuses(apps, schema_editor):
    TaskStatus = apps.get_model("assets", "TaskStatus")
    db_alias = schema_editor.connection.alias
    TaskStatus.objects.using(db_alias).bulk_create([
        TaskStatus(name="Completed")
    ])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'task statuses',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='taskcompletion',
            name='task',
        ),
        migrations.DeleteModel(
            name='TaskCompletion',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='status',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='assets.TaskStatus'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.Task'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(add_task_statuses)
    ]
