# Generated by Django 2.0.7 on 2018-07-15 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_taskcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assets.Asset'),
        ),
    ]
