# Generated by Django 2.0.7 on 2018-07-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_task_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-date'], 'verbose_name_plural': 'task history'},
        ),
    ]
