# Generated by Django 2.1 on 2018-08-26 19:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180823_1639'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='asset',
            managers=[
                ('for_team', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='assettype',
            managers=[
                ('for_team', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('for_team', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='note',
            managers=[
                ('for_team', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('for_team', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='taskhistory',
            managers=[
                ('for_team', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='taskpriority',
            managers=[
                ('for_team', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tasktype',
            managers=[
                ('for_team', django.db.models.manager.Manager()),
            ],
        ),
    ]
