# Generated by Django 3.2.4 on 2021-06-09 13:30

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assettype_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
