# Generated by Django 2.0.7 on 2018-07-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180720_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
