# Generated by Django 2.1.15 on 2021-06-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
