# Generated by Django 3.2.4 on 2021-06-18 10:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20210610_1609'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='asset',
            managers=[
                ('for_collection', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='assettype',
            managers=[
                ('for_collection', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('for_collection', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('for_collection', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='taskhistory',
            managers=[
                ('for_collection', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='taskpriority',
            managers=[
                ('for_collection', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tasktype',
            managers=[
                ('for_collection', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField('asset', 'team', 'collection'),
        migrations.RenameField('contact', 'team', 'collection'),
        migrations.RenameField('assettype', 'team', 'collection'),
        migrations.RenameField('taskpriority', 'team', 'collection'),
        migrations.RenameField('tasktype', 'team', 'collection'),
        migrations.AlterUniqueTogether(
            name='assettype',
            unique_together={('collection', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskpriority',
            unique_together={('collection', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tasktype',
            unique_together={('collection', 'name')},
        ),
    ]
