# Generated by Django 3.2.4 on 2021-06-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20210618_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpriority',
            name='badge_colour',
            field=models.CharField(default='#f0f0f0', max_length=7),
        ),
        migrations.AddField(
            model_name='taskpriority',
            name='font_colour',
            field=models.CharField(default='#3e3e3e', max_length=7),
        ),
    ]
