# Generated by Django 2.1.15 on 2021-06-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20210602_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpriority',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'task priorities'},
        ),
        migrations.AddField(
            model_name='taskpriority',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
