# Generated by Django 2.0.7 on 2018-07-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
