# Generated by Django 2.0.7 on 2018-07-24 22:27

from django.db import migrations, models


def update_schedule(apps, schema_editor):
    Task = apps.get_model("assets", "Task")
    db_alias = schema_editor.connection.alias
    for t in Task.objects.using(db_alias).all():
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat_frequency',
            field=models.IntegerField(blank=True, choices=[(3, 'Day(s)'), (2, 'Week(s)'), (1, 'Month(s)'), (0, 'Year(s)')], null=True),
        ),
        migrations.RunPython(update_schedule),
    ]
