# Generated by Django 2.0.7 on 2018-07-25 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0009_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
