# Generated by Django 2.1 on 2018-08-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_note_shared_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'task priorities',
                'ordering': ['name'],
            },
        ),
    ]
