# Generated by Django 2.1 on 2018-08-02 22:22

from django.db import migrations


def add_task_statuses(apps, schema_editor):
    Status = apps.get_model("assets", "Status")
    db_alias = schema_editor.connection.alias
    Status.objects.using(db_alias).get_or_create(name="Completed")


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_task_task_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskStatus',
            new_name='Status',
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name_plural': 'statuses'},
        ),
        migrations.RunPython(add_task_statuses)
    ]
