# Generated by Django 2.1 on 2018-08-21 13:44

import authentication.middleware.current_user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_activated_team'),
        ('assets', '0014_auto_20180803_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='team',
            field=models.ForeignKey(default=authentication.middleware.current_user.get_current_team, editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.Team'),
        ),
    ]
