# Generated by Django 2.1 on 2018-08-21 14:12

import authentication.middleware.current_user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_activated_team'),
        ('assets', '0016_contact_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='team',
            field=models.ForeignKey(default=authentication.middleware.current_user.get_current_team, editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.Team'),
        ),
        migrations.AddField(
            model_name='taskpriority',
            name='team',
            field=models.ForeignKey(default=authentication.middleware.current_user.get_current_team, editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.Team'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='team',
            field=models.ForeignKey(default=authentication.middleware.current_user.get_current_team, editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.Team'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='assettype',
            unique_together={('team', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskpriority',
            unique_together={('team', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tasktype',
            unique_together={('team', 'name')},
        ),
    ]
