# Generated by Django 2.1 on 2018-08-21 20:05

import authentication.middleware.current_user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_activated_team'),
        ('assets', '0017_auto_20180821_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='shared_users',
        ),
        migrations.AddField(
            model_name='note',
            name='team',
            field=models.ForeignKey(default=authentication.middleware.current_user.get_current_team, editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.Team'),
        ),
    ]
