# Generated by Django 3.2.4 on 2021-06-18 10:54

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Team', 'Collection'),
        migrations.RenameField('user', 'activated_team', 'activated_collection'),
        migrations.AlterField(
            model_name='collection',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='guested_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
