# Generated by Django 2.1 on 2018-08-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20180407_2058'),
        ('authentication', '0002_user_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
    ]
